meta_product_name: "SocksUp"
meta_title: "SocksUp - Get Experience. Get Paid. Get Exploring."
meta_description: "A website which connects young people who lack CV content with
their first jobs by showcasing their skills through quizzes. 🧦❤️"
meta_image: "socksup-share-image.png"
